Lesson 1. Factorial calculation
js-tasks-ru/jsbasic-20230116-2_mihail-milem pull request #2
Opened 2023-01-17 16:15 UTC by Gvelet

2023-01-17 16:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-17 16:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-17 16:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-17 17:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-18 16:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-20 12:39 UTC, SinimaWath requested changes

2023-01-20 12:39 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return (name === '' || name === null || name.includes(' ') || name.length < 4) ? false : true
`name === '' || name === null` -> можно заменить до: `!name`

Также тут можно не использовать тернарный оператор:
`return Boolean(name) && ... && ...`

2023-01-21 14:46 UTC, Gvelet commented on 1-module/2-task/index.js
> +  return (name === '' || name === null || name.includes(' ') || name.length < 4) ? false : true
С первой часть все понятно
А со второй так и не понял что сделать:
Если написать буквально 
  return Boolean(name) && !name && name.includes(' ') && name.length < 4
  То все равно по тестам не прохожу. Перепробовал кучу всего, но так и не смог дойти до решения без явного указания что при условии будет false иначе true:((

2023-01-21 14:58 UTC, Gvelet commented on 1-module/2-task/index.js
> +  return (name === '' || name === null || name.includes(' ') || name.length < 4) ? false : true
Ну или вот так **return !(!name || name.includes(' ') || name.length < 4)**

2023-01-21 15:00 UTC, Gvelet commented on 1-module/2-task/index.js
> +  return (name === '' || name === null || name.includes(' ') || name.length < 4) ? false : true
С первой часть все понятно
Но во второй я максимум к чему пришел, это вот к этому: **return !(!name || name.includes(' ') || name.length < 4)**

Можно узнать ваше решение?

2023-01-21 19:26 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return (name === '' || name === null || name.includes(' ') || name.length < 4) ? false : true
`return Boolean(name) && !name.includes(' ') && name.length >= 4`

2023-01-21 20:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-23 15:52 UTC, SinimaWath approved these changes

2023-01-23 15:53 UTC, merged