4 Модуль
js-tasks-ru/jsbasic-20230116-2_mihail-milem pull request #5
Opened 2023-01-31 18:33 UTC by Gvelet

2023-01-31 18:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-31 19:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-01 18:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-02 23:26 UTC, SinimaWath requested changes

2023-02-02 23:26 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    for(let j = 0; j < tableRow[j].children.length; j++){
тут кажется должен быть: `tableRow[i].children.length`, а не j

2023-02-03 07:53 UTC, Gvelet commented on 4-module/3-task/index.js
> +    for(let j = 0; j < tableRow[j].children.length; j++){
Хм, да. Тесты прошли, но у меня вопросы:
1)У меня же все и так работало по функционалу - поменял, ничего не изменилось, кроме того что тесты прошли
2)tableRow[i].children.length и tableRow[j].children.length - выводят же то же самое, я посмотрел на вывод в console.log
3)Если это все так ошибка была, почему мне тогда в консоль не сыпались ошибки? а только при тестах

2023-02-03 07:54 UTC, Gvelet commented on 4-module/3-task/index.js
> +    for(let j = 0; j < tableRow[j].children.length; j++){
4)Решил попробовать опять свой вариант, поменял и тесты прошли. Ничего не понимаю что происходит)))

2023-02-03 07:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-03 11:03 UTC, Gvelet commented on 4-module/3-task/index.js
> +    for(let j = 0; j < tableRow[j].children.length; j++){
4)И что с задачей в целом? Просидел очень долго и методом перебора, пришел только к такому решению. Насколько оно хорошее и как его можно было бы сделать лучше?

2023-02-03 13:34 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    for(let j = 0; j < tableRow[j].children.length; j++){
1 - посмотрел на вывод в консоли, там должна быть ошибка. у тебя i - это индекс строчки, j - это индекс столбика, то что работало, просто повезло, что i === j

2023-02-03 13:35 UTC, SinimaWath approved these changes
Решение хорошее, в целом тут сложно что-то улучшить

2023-02-03 13:36 UTC, merged